export class AudioEngine{
 constructor(){this.enabled=true;this.ctx=null;this.master=null;this.trackGain=null;}
 unlock(){if(!this.enabled)return;try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.18;this.master.connect(this.ctx.destination);this.startTracks();}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{}}
 toggle(){this.enabled=!this.enabled;if(this.master)this.master.gain.setTargetAtTime(this.enabled?.18:0,this.ctx.currentTime,.04);if(this.enabled)this.unlock();return this.enabled;}
 tone(freq,duration,volume=.2,delay=0,type='sine'){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration+.02);}
 shot(){if(!this.enabled||!this.ctx)return;const c=this.ctx,t=c.currentTime,b=c.createBuffer(1,Math.floor(c.sampleRate*.09),c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.exp(-i/a.length*7);const n=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();n.buffer=b;f.type='lowpass';f.frequency.value=950;g.gain.value=.48;n.connect(f);f.connect(g);g.connect(this.master);n.start();this.tone(95,.09,.26);}
 hit(){this.tone(660,.17,.17,.045);this.tone(880,.26,.13,.11);}
 win(){[523.25,659.25,783.99,1046.5].forEach((n,i)=>this.tone(n,.48,.16,i*.14));}
 startTracks(){const c=this.ctx,b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(.4+.6*Math.pow(Math.sin(i/c.sampleRate*28),8));const n=c.createBufferSource(),f=c.createBiquadFilter();n.buffer=b;n.loop=true;f.type='lowpass';f.frequency.value=230;this.trackGain=c.createGain();this.trackGain.gain.value=0;n.connect(f);f.connect(this.trackGain);this.trackGain.connect(this.master);n.start();}
 moving(value){if(this.trackGain)this.trackGain.gain.setTargetAtTime(value&&this.enabled?.12:0,this.ctx.currentTime,.18);}
}
